# Generated by Django 5.2.15 on 2026-07-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_order_product_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditblock',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
