# Generated by Django 5.2.15 on 2026-07-02 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_auditblock_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('legal_name', models.CharField(max_length=100)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('base_currency', models.CharField(default='INR', max_length=3)),
                ('show_currency_on_orders', models.BooleanField(default=False)),
                ('default_delivery_sales_days', models.IntegerField(default=14)),
                ('default_lead_purchase_days', models.IntegerField(default=14)),
                ('current_plan_tier', models.CharField(default='Free', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='inventory.company')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_monthly_sales', models.IntegerField(default=1000)),
                ('has_manufacturing_mgmt', models.BooleanField(default=False)),
                ('has_shop_floor_app', models.BooleanField(default=False)),
                ('has_traceability', models.BooleanField(default=False)),
                ('has_warehouse_mgmt', models.BooleanField(default=True)),
                ('calculated_total_due', models.DecimalField(decimal_places=2, default=746.0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='inventory.company')),
            ],
        ),
    ]
